Data Preprocessing
This notebook focuses on feature selection and preprocessing for the Premier League match outcome prediction model.

In [1]:
import pandas as pd

data = pd.read_csv("epl_cleaned.csv")
data.head()

,Date,Season,HomeTeam,AwayTeam,FTH Goals,FTA Goals,FT Result,H Shots,A Shots,H SOT,...,A Fouls,H Corners,A Corners,H Yellow,A Yellow,H Red,A Red,Display_Order,League,home_win
0,16/01/2025,2024/25,Ipswich Town,Brighton & Hove Albion,0,2,A,5.0,11.0,3.0,...,14.0,1.0,9.0,2.0,2.0,0.0,0.0,20250116,Premier League,0
1,16/01/2025,2024/25,Man United,Southampton,3,1,H,23.0,13.0,9.0,...,10.0,4.0,4.0,1.0,3.0,0.0,0.0,20250116,Premier League,1
2,15/01/2025,2024/25,Everton,Aston Villa,0,1,A,10.0,11.0,3.0,...,10.0,8.0,5.0,2.0,1.0,0.0,0.0,20250115,Premier League,0
3,15/01/2025,2024/25,Leicester,Crystal Palace,0,2,A,21.0,9.0,4.0,...,6.0,4.0,3.0,0.0,0.0,0.0,0.0,20250115,Premier League,0
4,15/01/2025,2024/25,Newcastle,Wolves,3,0,H,17.0,13.0,5.0,...,13.0,4.0,2.0,0.0,2.0,0.0,0.0,20250115,Premier League,1

Feature Selection

To avoid data leakage, features that directly describe the match outcome (such as full-time goals and result) are excluded.  
Only match statistics such as shots, fouls, corners, and disciplinary records are used as input features.

In [2]:
#drop leakage columns
leakage_cols = [
    "FT Result", "FTH Goals", "FTA Goals",
    "HomeTeam", "AwayTeam",
    "Date", "Season", "League", "Display_Order"
]

data = data.drop(columns=leakage_cols, errors="ignore")
data.head()

,H Shots,A Shots,H SOT,A SOT,H Fouls,A Fouls,H Corners,A Corners,H Yellow,A Yellow,H Red,A Red,home_win
0,5.0,11.0,3.0,5.0,13.0,14.0,1.0,9.0,2.0,2.0,0.0,0.0,0
1,23.0,13.0,9.0,5.0,7.0,10.0,4.0,4.0,1.0,3.0,0.0,0.0,1
2,10.0,11.0,3.0,3.0,17.0,10.0,8.0,5.0,2.0,1.0,0.0,0.0,0
3,21.0,9.0,4.0,4.0,7.0,6.0,4.0,3.0,0.0,0.0,0.0,0.0,0
4,17.0,13.0,5.0,7.0,10.0,13.0,4.0,2.0,0.0,2.0,0.0,0.0,1

In [3]:
#defining x and y
X = data.drop(columns=["home_win"])
y = data["home_win"]

X.shape, y.shape

((12153, 12), (12153,))

Preprocessing Summary

After removing leakage-prone and non-informative columns, the final feature matrix consists of numerical match statistics.  
These features are suitable for training classification models without introducing bias from the target variable.